#!/bin/bash

SESH="dev-env"

tmux has-session -t $SESH 2>/dev/null

if [ $? != 0 ]; then
    tmux new-session -d -s $SESH -n "home"
    tmux send-keys -t $SESH:home "cd ~" C-m
    tmux send-keys -t $SESH:home "clear" C-m

    tmux new-window -t $SESH -n "root"
    tmux send-keys -t $SESH:root "source venv" C-m
    tmux send-keys -t $SESH:root "clear" C-m

    tmux new-window -t $SESH -n "code"
    tmux send-keys -t $SESH:code "nvim" C-m

    tmux select-window -t $SESH:root
fi

tmux attach-session -t $SESH
